### ISSUE TITLE
Replace `flatten_nested` rules with a generic form

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#491]
## Description

Replace the rules `flatten_nested_sum`, `unwrap_nested_or`, `unwrap_nested_and`, etc. with a generic rule ~~`flatten_nested_vecop`~~ `normalise_associative_commutative`:  
  
```
v(v(a,b,...),c,d,...) ~> v(a,b,c,d)
where v is an AC vector operator
``` 

## Prerequisites

- [x] #494

**Comment by niklasdewally** [comment]
They definitely need renaming; thanks for the suggestion!

@ozgurakgun along similar lines, would merging the rules that deal with vector operations with only one element be a good idea? ( for example `remove_trivial_or`). They also definitely need renaming to something consistent - I was thinking `remove_unit_vector`?

**Comment by niklasdewally** [comment]
> The common property you want from these operators is that they are commutative and associative. This is why SR has a special AC-CSE for example.

`normalise_associative_operator` ok?

**Comment by ozgurakgun** [comment]
remove_unit_vector sounds good to me. 

empty vectors cannot be handled generically though since the behaviour depends on the identity element of the operator. 

For every AC operator we could have a triplet defined: identity, binary operator, skipping operator. The first two are hopefully clear, the third is a bit weird but useful. 

Let's take sum as an example. 0 is the identity, + is the binop, `\ (b, x) -> toInt(b) * x` is the skipping operator. 

Skipping op evaluates to identity if b is false, to the second argument if b is true. 

For logical and it is `\ (b, x) -> b => x`

For logical or it is `\ (b, x) -> b /\ x`

Using pseudo Haskell/Essence syntax here, hopefully you can follow it! Happy to discuss further of course.

**Comment by ozgurakgun** [comment]
> > The common property you want from these operators is that they are commutative and associative. This is why SR has a special AC-CSE for example.
> 
> 
> 
> `normalise_associative_vecop` ok?
> 
> 
> 
> (assuming that we will need `normalise_associative_binop` down the line)

I'd also use commutative here. Associative doesn't imply commutative in general and both are important here. Use normalise_associative_commutative and we can implement both vec and bin versions in the same rule?

**Comment by niklasdewally** [comment]
> I'd also use commutative here. Associative doesn't imply commutative in general and both are important here. Use normalise_associative_commutative and we can implement both vec and bin versions in the same rule?

Remembering previous conversations, we don't want to use commutativity to reorder elements right?

**Comment by ozgurakgun** [comment]
> When will this skipping operator come in handy?

You'll see when you get to comprehensions / quantified expressions :)

**Comment by ozgurakgun** [comment]
> Remembering previous conversations, we don't want to use commutativity to reorder elements right, so this rule would just do associativty?

I am starting to think you'd want to order as well. It might allow more CSE down the line for example. I cannot think of a downside. 

I didn't want to use a self-sorting (or orderless) data structure because things like pretty printing or debugging might become more cryptic with those. But normalising like this should be ok. What we need to avoid is repeatedly checking whether an expression is in normal form, but I am thinking this would be avoided via the rule precedences anyway.

**Comment by niklasdewally** [comment]
> > Remembering previous conversations, we don't want to use commutativity to reorder elements right, so this rule would just do associativty?
> 
> I am starting to think you'd want to order as well. It might allow more CSE down the line for example. I cannot think of a downside. 
> 
> I didn't want to use a self-sorting (or orderless) data structure because things like pretty printing or debugging might become more cryptic with those. But normalising like this should be ok. What we need to avoid is repeatedly checking whether an expression is in normal form, but I am thinking this would be avoided via the rule precedences anyway.

In that case, should I split up the associativity bit of the rule (removing brackets) and the commutativity bit?

Ie have:

* normalise_associative_commutative_associativity

* normalise_associative_commutative_commutatitity?

Or would one big rule be fine?

**Comment by ozgurakgun** [comment]
(Feel free to wait until our next meeting if you are concerned about a moving goal post wrt ordering by the way.)

**Comment by ozgurakgun** [comment]
> Or would one big rule be fine?

I don't see an advantage of separating these two, so I vote for one big rule.

**Comment by niklasdewally** [comment]
This is blocked until I fix <_ as Biplate<Vec<Expr>>.

I need to do

```rs
/// Normalises associative_commutative operations.
///
/// For now, this just removes nested expressions by associativity.
///
/// ```text
/// v(v(a,b,...),c,d,...) ~> v(a,b,c,d)
/// where v is an AC vector operator
/// ```
#[register_rule(("Base", 8400))]
fn normalise_associative_commutative(expr: &Expr, _: &Model) -> ApplicationResult {
    
    if !expr.is_associative_commutative_operator() {
         return Err(RuleNotApplicable);
     }

     let mut new_children: Vec<Expr> = vec![];
     let mut changed = false;
     for child in <_ as Biplate<Vec<Expr>>::children_bi(expr)[0] {
         // same enum variant?
         if std::mem::discriminant(expr) == std::mem::discriminant(&child) {
             new_children.extend(child.children());
             changed = true;
         } else {
             new_children.push(child);
         }
  }
}
```

I think this is the first rule that is impossible to write without Uniplate! 
You could do the below:
```rs
match e {
  Sum(_,vs) => (vs,|vs| Sum(_,vs))
...
```

but that is just the definition of `Biplate<Vec<Expr>>` for `Vec<Expr>`!
