### ISSUE TITLE
Remove .unwrap() and .expects() from Minion bindings.

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#78]
See clippy output - these shouldn't be used and an error should be thrown upwards instead.

**Comment by ChrisJefferson** [comment]
These all look fine to me, but as a general comment, I'm personally not against fairly generous use of `.expect()`, because if some solver's internal state could be half-built, it might not be possible to fix things. At the least, having tests which hit all these error cases, and check the system continues to function correctly afterwards, would be a good long-term aim (but I don't think they are needed now, as things are in flux).

Also, it might be nice for some of them to have nicer names, for example (I think) the CString::new are something like "variable names cannot contain the null character".
