### ISSUE TITLE
Support Minion Sparse Bound

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#84]
Currently, variables with multiple ranges are not supported by Minion.
Support the use of Minion's sparse bound to allow the finding of these variables.

This needs to implemented in three layers of the stack:

1. libminion (inside minion's source code).
2. `minion_rs`
3. The `TryFrom` implementation for Minion in `conjure_oxide`.

**Comment by ChrisJefferson** [comment]
This is some minion knowledge I'm not sure is documented well anywhere :)

My advice for starting out is to just use BOOL and DISCRETE. BOUND and SPARSEBOUND have the advantage that they take up O(log n) space instead of O(n) space, so they are better for bigger variables -- but some constraints do not support BOUND and SPARSEBOUND, so you need to carefully match the constraints to the variables (for all constraints, there is some implementation that supports BOUND and SPARSEBOUND -- there is a whole other discussion on how some constraints are implemented multiple times, and one has to choose between them).

So, how do you do a variable with multiple ranges? Using the w-inintervalset constraint

w-inintervalset
^^^^^^^^^^^^^^^

The constraint w-inintervalset(x, [a1,a2, b1,b2, ... ]) ensures that the
value of x belongs to one of the intervals {a1,...,a2}, {b1,...,b2} etc.
The list of intervals must be given in numerical order.
