### ISSUE TITLE
Representing Rewrite Rules, and Basic Rewriting Engine

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#96]
Details TBC, but some stuff about this is in the [High level plan](https://github.com/conjure-cp/conjure-oxide/wiki/High-Level-Plan).

**Comment by lixitrixi** [comment]
We've created a very basic macro to decorate rule functions over on #112 . This will make it trivial to register a new rule and allow use to easily organize them with different kinds (Horizontal, Vertical, Solver-Specific). I am currently working on a way to link these rules together using the macro to be able to retrieve them dynamically at compile time rather than having them all in a hard-coded registry.

I've attempted this already using the `inventory` crate but it is tricky since the macro has to be used in the same crate that the `Rule` type is defined. Another possible option is the `linkme` crate, which uses compiler tricks instead of life-before-main shenanigans and so should support inter-crate use.

@ozgurakgun once the registry is working we'll be able to retrieve rules by kind and apply them nicely. Do you feel that we've captured what's required to make a proper rewrite system so far?

**Comment by niklasdewally** [comment]
> once the registry is working we'll be able to retrieve rules by kind and apply them nicely. Do you feel that we've captured > what's required to make a proper rewrite system so far?

We still need to write the actual rewriting system itself :) 

But having a nice way to represent and add rules is an important thing to think about, and I think we settled on something good here - with a global registry we can semantically split rules into their own files and not have to worry about where anything is stored, which is a good thing.
